# Generated by Django 2.1.5 on 2019-02-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mercos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='lucro',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='precoCliente',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='receita',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
