# Generated by Django 2.1.5 on 2019-02-04 00:19

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mercos', '0002_auto_20190203_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempedido',
            name='modified_at',
            field=models.DateField(default=datetime.datetime(2019, 2, 4, 0, 19, 25, 752852, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
