# Generated by Django 2.1.5 on 2019-01-22 02:29

import backend_mercos.enums_merc
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mercos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='rentabilidade',
            field=models.CharField(choices=[(backend_mercos.enums_merc.TipoRentabilidade('Sem Rentabilidade'), 'Sem Rentabilidade'), (backend_mercos.enums_merc.TipoRentabilidade('Rentabilidade Ótima'), 'Rentabilidade Ótima'), (backend_mercos.enums_merc.TipoRentabilidade('Rentabilidade Boa'), 'Rentabilidade Boa'), (backend_mercos.enums_merc.TipoRentabilidade('Rentabilidade Ruim'), 'Rentabilidade Ruim')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='rentabilidade',
            field=models.CharField(choices=[(backend_mercos.enums_merc.TipoRentabilidade('Sem Rentabilidade'), 'Sem Rentabilidade'), (backend_mercos.enums_merc.TipoRentabilidade('Rentabilidade Ótima'), 'Rentabilidade Ótima'), (backend_mercos.enums_merc.TipoRentabilidade('Rentabilidade Boa'), 'Rentabilidade Boa'), (backend_mercos.enums_merc.TipoRentabilidade('Rentabilidade Ruim'), 'Rentabilidade Ruim')], max_length=50),
        ),
    ]
