# Generated by Django 2.1.5 on 2019-01-22 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mercos', '0002_auto_20190122_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ('nome',)},
        ),
    ]
