# Generated by Django 2.1.5 on 2019-01-23 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_mercos', '0004_auto_20190123_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='pedidos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend_mercos.Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backend_mercos.Usuario'),
        ),
    ]
